server:
  port: 8300
  servlet:
    context-path: /api
spring:
  application:
    name: fly_msg
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/furn?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 12345678
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
      table-underline: true # 开启驼峰转下划线映射
  type-aliases-package: com.juzi.furnbackend.model.entity
